apiVersion: v1
kind: Service
metadata:
  name: loan-approval-system
spec:
  selector:
    app: loan-approval-system
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
